import { invoke } from './backend';
import type { BackupPlan, CapacityCheck, CheckSummary, Comparison, Core, JournalSummary, LibraryScan, MediaScan, Plan, PlaylistPlan, Problem, Setting, SyncReport } from './types';

export const inspectCard = (path: string) => invoke<Core[]>('inspect_card', { path });
export const readPersistedSettings = (path: string) => invoke<Setting[]>('read_persisted_settings', { path });
export const readCheckSummary = (path: string) => invoke<CheckSummary | null>('read_check_summary', { path });
export const planSync = (sources: string[], destination: string, embedCovers: boolean) => invoke<Plan>('plan_sync', { sources, destination, embedCovers });
export const executeSync = (sources: string[], destination: string, confirmation: string, manifestPath: string, embedCovers: boolean, jobId: string) => invoke<SyncReport>('execute_sync', { sources, destination, confirmation, manifestPath, embedCovers, jobId });
export const compareMedia = (left: string, right: string) => invoke<Comparison>('compare_media', { left, right });
export const planCoreCopy = (source: string, destination: string) => invoke<Plan>('plan_core_copy', { source, destination });
export const executeCoreCopy = (source: string, destination: string, confirmation: string, manifestPath: string, jobId: string) => invoke<SyncReport>('execute_core_copy', { source, destination, confirmation, manifestPath, jobId });
export const executeCoreMove = (source: string, destination: string, confirmation: string, backupPath: string, manifestPath: string, jobId: string) => invoke<SyncReport>('execute_core_move', { source, destination, confirmation, deleteConfirmation: confirmation, backupPath, manifestPath, jobId });
export const scanMedia = (path: string, jobId: string) => invoke<MediaScan>('scan_media', { path, jobId });
export const exportPlaylist = (mediaRoot: string, playlistName: string, output: string) => invoke<void>('export_playlist', { mediaRoot, playlistName, output });
export const planPlaylistWrite = (path: string, file: string, tracks: string[]) => invoke<PlaylistPlan>('plan_playlist_write', { path, file, tracks });
export const executePlaylistWrite = (path: string, file: string, tracks: string[], confirmation: string) => invoke<void>('execute_playlist_write', { path, file, tracks, confirmation });
export const planPlaylistRename = (path: string, oldFile: string, newFile: string) => invoke<PlaylistPlan>('plan_playlist_rename', { path, oldFile, newFile });
export const executePlaylistRename = (path: string, oldFile: string, newFile: string, confirmation: string) => invoke<void>('execute_playlist_rename', { path, oldFile, newFile, confirmation });
export const planPlaylistImport = (path: string, source: string, destFile: string) => invoke<PlaylistPlan>('plan_playlist_import', { path, source, destFile });
export const executePlaylistImport = (path: string, source: string, destFile: string, confirmation: string) => invoke<void>('execute_playlist_import', { path, source, destFile, confirmation });
export const findProblems = (path: string) => invoke<Problem[]>('find_problems', { path });
export const readJournal = (path: string) => invoke<unknown>('read_journal', { path });
export const listJournals = (dir: string) => invoke<JournalSummary[]>('list_journals', { dir });
export const getReportsDir = () => invoke<string | null>('get_reports_dir');
export const setReportsDir = (path: string) => invoke<void>('set_reports_dir', { path });
export const scanLibrary = (path: string, jobId: string) => invoke<LibraryScan>('scan_library', { path, jobId });
export const checkStorageCapacity = (path: string, bytesNeeded: number) => invoke<CapacityCheck>('check_storage_capacity', { path, bytesNeeded });
export const planBackup = (source: string, destination: string) => invoke<BackupPlan>('plan_backup', { source, destination });
export { cancelJob, newJobId, onProgress, errorMessage } from './backend';
