import { invoke } from './backend';
import type { BackupPlan, CapacityCheck, CheckSummary, Comparison, Core, JournalSummary, LibraryScan, MediaScan, PackageManifest, PackagePlan, PackageReport, Plan, PlaylistPlan, Problem, RemovePlan, RemoveReport, ScreenshotEntry, Setting, SyncReport, TaudReport } from './types';

export const inspectCard = (path: string) => invoke<Core[]>('inspect_card', { path });
export const readPersistedSettings = (path: string) => invoke<Setting[]>('read_persisted_settings', { path });
export const readCheckSummary = (path: string) => invoke<CheckSummary | null>('read_check_summary', { path });
export const planSync = (sources: string[], destination: string, embedCovers: boolean) => invoke<Plan>('plan_sync', { sources, destination, embedCovers });
export const executeSync = (sources: string[], destination: string, confirmation: string, manifestPath: string, embedCovers: boolean, jobId: string) => invoke<SyncReport>('execute_sync', { sources, destination, confirmation, manifestPath, embedCovers, jobId });
export const compareMedia = (left: string, right: string) => invoke<Comparison>('compare_media', { left, right });
export const planCoreCopy = (source: string, destination: string) => invoke<Plan>('plan_core_copy', { source, destination });
export const executeCoreCopy = (source: string, destination: string, confirmation: string, manifestPath: string, jobId: string) => invoke<SyncReport>('execute_core_copy', { source, destination, confirmation, manifestPath, jobId });
export const executeCoreMove = (source: string, destination: string, confirmation: string, backupPath: string, manifestPath: string, jobId: string) => invoke<SyncReport>('execute_core_move', { source, destination, confirmation, deleteConfirmation: confirmation, backupPath, manifestPath, jobId });
export const scanMedia = (path: string, jobId: string) => invoke<MediaScan>('scan_media', { path, jobId });
export const exportPlaylist = (mediaRoot: string, playlistName: string, output: string) => invoke<void>('export_playlist', { mediaRoot, playlistName, output });
export const planPlaylistWrite = (path: string, file: string, tracks: string[]) => invoke<PlaylistPlan>('plan_playlist_write', { path, file, tracks });
export const executePlaylistWrite = (path: string, file: string, tracks: string[], confirmation: string) => invoke<void>('execute_playlist_write', { path, file, tracks, confirmation });
export const planPlaylistRename = (path: string, oldFile: string, newFile: string) => invoke<PlaylistPlan>('plan_playlist_rename', { path, oldFile, newFile });
export const executePlaylistRename = (path: string, oldFile: string, newFile: string, confirmation: string) => invoke<void>('execute_playlist_rename', { path, oldFile, newFile, confirmation });
export const planPlaylistImport = (path: string, source: string, destFile: string) => invoke<PlaylistPlan>('plan_playlist_import', { path, source, destFile });
export const executePlaylistImport = (path: string, source: string, destFile: string, confirmation: string) => invoke<void>('execute_playlist_import', { path, source, destFile, confirmation });
export const findProblems = (path: string) => invoke<Problem[]>('find_problems', { path });
export const readJournal = (path: string) => invoke<unknown>('read_journal', { path });
export const listJournals = (dir: string) => invoke<JournalSummary[]>('list_journals', { dir });
export const getReportsDir = () => invoke<string | null>('get_reports_dir');
export const setReportsDir = (path: string) => invoke<void>('set_reports_dir', { path });
export const getRecentCards = () => invoke<string[]>('get_recent_cards');
export const recordRecentCard = (path: string) => invoke<void>('record_recent_card', { path });
export const listMountedCards = () => invoke<string[]>('list_mounted_cards');
export const getManualPlayers = () => invoke<string[]>('get_manual_players');
export const setManualPlayer = (coreId: string, enabled: boolean) => invoke<void>('set_manual_player', { coreId, enabled });
export const scanLibrary = (path: string, jobId: string) => invoke<LibraryScan>('scan_library', { path, jobId });
export const checkStorageCapacity = (path: string, bytesNeeded: number) => invoke<CapacityCheck>('check_storage_capacity', { path, bytesNeeded });
export const planBackup = (source: string, destination: string) => invoke<BackupPlan>('plan_backup', { source, destination });
export const inspectPackage = (path: string) => invoke<PackageManifest>('inspect_package', { path });
export const planPackageInstall = (path: string, card: string) => invoke<PackagePlan>('plan_package_install', { path, card });
export const executePackageInstall = (path: string, card: string, confirmation: string) => invoke<PackageReport>('execute_package_install', { path, card, confirmation });
export const planRemoveCore = (card: string, coreId: string) => invoke<RemovePlan>('plan_remove_core', { card, coreId });
export const executeRemoveCore = (card: string, coreId: string, confirmation: string) => invoke<RemoveReport>('execute_remove_core', { card, coreId, confirmation });
export const readQrReport = (path: string) => invoke<TaudReport | null>('read_qr_report', { path });
export const listScreenshots = (card: string) => invoke<ScreenshotEntry[]>('list_screenshots', { card });
export const readImageDataUrl = (path: string) => invoke<string>('read_image_data_url', { path });
export { cancelJob, newJobId, onProgress, errorMessage } from './backend';
